export const ADD_DATATOBASKET = "ADD_DATATOBASKET";
export const CLEAR_BASKET = "CLEAR_BASKET";
export const VIEW_DATATOBASKET = "VIEW_DATATOBASKET";

export const ADD_PRODUCTDATA = "ADD_PRODUCTDATA";
export const VIEW_PRODUCTDATA = "VIEW_PRODUCTDATA";

export const ADD_DATA = "ADD_DATA";
export const VIEW_DATA = "VIEW_DATA";

export const SET_LANG = "SET_LANG";
export const INCREASE_TO_BASKET_PRODUCT="INCREASE_TO_BASKET_PRODUCT";